os:
  - linux
  - osx
sudo: false

language: node_js
node_js:
  - "10"

addons:
  firefox: latest
  chrome: stable

cache:
  directories:
    - ./node_modules

install:
  - npm install

script:
  - npm run test -- carousel --watch false
